### ISSUE TITLE
Unable to format 3.10 code with a `match` statement

### ISSUE THREAD

**Issue by cooperlees** [facebook/usort#216]
I believe I have valid python 3.10 syntax in [nmapsanner.py](https://github.com/cooperlees/nmapscanner/blob/main/nmapscanner.py#L220) as my running + unittests pass. Should this code be supported by usort main? If not, here is some sample code to work with to add support.

## Error and repro

- `git clone git@github.com:cooperlees/nmapscanner.git`
- `python3 -m venv /tmp/test_usort`
- `/tmp/test_usort/bin/pip install git+https://github.com/facebook/usort`

```
cooper@l33t:~/repos/nmapscanner$ /tmp/test_usort/bin/usort check .
Error sorting nmapscanner.py: Syntax Error @ 220:11.
Incomplete input. Encountered 'output_format', but expected ';', or 'NEWLINE'.

    match output_format:
          ^
Would sort nmapscanner.py
```

Cheers

**Comment by amyreese** [comment]
I think this is because LibCST only supports 3.10 syntax using the new rust parser, which is not yet enabled by default. Try setting `LIBCST_PARSER_TYPE="native"` in your environment when running µsort:

```
$ LIBCST_PARSER_TYPE=native usort check .
```

**Comment by cooperlees** [comment]
Yup, that works. Should that be documented somewhere to save others being confused? What's the default plan? Can it maybe be default / set for >= 3.10? 3.10 is pretty common now.

```
crl-m1:usort cooper$ grep -R LIBCST_PARSER_TYPE *
crl-m1:usort cooper$
```
